### ISSUE TITLE
Tilda stop responding to pull up/down key after closing the preference dialog

### ISSUE THREAD

**Issue by sudaraka** [lanoxx/tilda#86]
Reproduce:
- Open Tilda window
- Right click -> Preferences
- Close preference dialog
- Press pull up/down key (F12 in my case) and window stays open

Problem was introduced in the commit ad12e4d4a019d9cfdf1cbf9277a39876c6e45925, by digging around the code I found that after closing the preference dialog, it stop calling the focus_out_event_cb on focus out events. My understanding of the language and GTK is not enough to come up with a solution, however glad to provide any further details if necessary.

P.s.
I'm using a tiling window manager (i3wm), not sure if that has anything to do with this.

**Comment by patrick-brian-mooney** [comment]
Affects me too, using both MATE and Openbox both in Linux Mint 18.2 and Crunchbang++ 9. The problem seems to be that I can't pull the Tilda terminal up when it is in focus, and the only thing that changes the focus effectively is using the mouse to click on another window. (Alt+Tab doesn't effectively change focus for purposes of the "can I pull the Tilda window up?" question.) It doesn't seem to matter whether the mouse is or is not currently hovering over the Tilda window.

So I can pull the Tilda window down by using F12, but pulling it back up requires that I take my hands off the keyboard, move the mouse to another window, click somewhere in the window (picking somewhere in the window that doesn't cause an action to occur), and then move my hands back to the keyboard and hit F12 twice.

Super annoying. :(

**Comment by mlmullens** [comment]
I just ran into what appears to be similar behavior as that reported here on on tilda 1.3.1. Will try building from source to see.

**Comment by lanoxx** [comment]
Which window manager are you using?

**Comment by mlmullens** [comment]
cinnamon

**Comment by mlmullens** [comment]
Built from master this morning and still experiences the same issue but have not debugged yet.

**Comment by mlmullens** [comment]
FIXED IT! Strange, there is a setting "Non-focus Pull Up Behavior" that has to be set to "Hide Terminal" to get my preferred behavior back.  So let that be a tip for anyone experiencing similar issue, check this setting! Whew, that was driving me nuts!

**Comment by Piplopp** [comment]
Hello !

Same issue here, tilda 1.3.1 and the windows manage being Cinnamon 3.2.7.
After uninstalling and reinstalling via sources the issue is still there. It seems that the issue happens when you try to change the hotkey, I can open/close the preference tab just fine as long as I don't change the hotkey to pull up/down.
